# Nearest Neighbors Algorithm for Supervised Learning


Nearest neighbors algorithms (NNAs) are very simple conceptually: to classify a datum with specific feature values, find the data point that has the most similar feature values and put the original datum in that class. NNAs can also be used to predict missing feature values. 

The most common NNA is the k-Nearest Neighbors algorithm where the top *K* nearest neighbors to the query are identified. In most instantiations of k-NNA, classification/prediction is based on a "majority vote" of the k nearest neighbors (ex. if k = 5 and 3 out of the 5 nearest neighbors are class A and 2 are class B, the new data point will be classified as A). In the image below, using k = 1 would yield a class 1 classification while k = 3 would yield class 2.


![alt text](https://cdn-images-1.medium.com/max/1600/0*Sk18h9op6uK9EpT8.)


----

### A quick example to illustrate k-NNA:

If we want to classify a car as "cool" or "uncool" using the features *horsepower, number of seats,* and *manual (0) or automatic (1)*, our dataset might look like this:

*   150, 5, 0, uncool (2008 Honda Civic)  
*   320, 5, 0, cool (2011 Dodge Charger)
*   383, 3, 1, cool (1985 Chevy Blazer)
*   210, 7, 0, uncool (2001 Honda Odyssey)

Let's say we're trying to predict whether the 2017 Bugatti Veyron (1500hp, 2 seats, manual: 1) is cool or not. In the next cell the data is loaded.

In [0]:
import numpy as np
import pandas as pd
import time

In [2]:
cars_dict = {'2008 Honda Civic':    {'hp':150., 'seats':5., 'auto':0., 'cool':0}, 
             '2011 Dodge Charger' : {'hp':320., 'seats':5., 'auto':0., 'cool':1}, 
             '1985 Chevy Blazer':   {'hp':383., 'seats':3., 'auto':1., 'cool':1}, 
             '2001 Honda Odyssey':  {'hp':210., 'seats':7., 'auto':0., 'cool':0}, 
             '2017 Bugatti Veyron': {'hp':1500.,'seats':2., 'auto':1., 'cool':None}}

data = pd.DataFrame.from_dict(cars_dict,orient='index')
data

                         hp  seats  auto  cool
1985 Chevy Blazer     383.0    3.0   1.0   1.0
2001 Honda Odyssey    210.0    7.0   0.0   0.0
2008 Honda Civic      150.0    5.0   0.0   0.0
2011 Dodge Charger    320.0    5.0   0.0   1.0
2017 Bugatti Veyron  1500.0    2.0   1.0   NaN

### Normalizing Data and Calculating Distance

In order to tell how "near" one datum is to another, we need a way to measure the distance between two data. One of the simplest ways to do this (and the way we will be doing it) is with simple Euclidian distance (formula below). Euclidean distance is the square root of the sum of the difference between each feature squared:

![alt text](https://i.stack.imgur.com/2y0bx.png.)

Some other approaches include Chi square distance and cosine distance (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4978658/). 

NOTE: By normalizing the data in this way we are assuming all features are equally important, but there are ways to weight some features more/less than others.

If we simply compute the Euclidean distance from one datum to another, values that are generally larger (like horsepower) will end up having a greater effect than the other smaller values. Because features with large values are not inherently more important for prediction than other values, we should normalize the data before we calculate distance. One quick and easy way to normalize data is to divide each datum by the maximum value in its category (i.e. divide each element in a row by the max value in that row).

In [3]:
# Normalize the data by dividing each value by the maximum value in its row. 
# Do not normalize the labels indicating cool and uncool (row 3)

for i in ['hp','seats','auto']:
    data[i] = data[i]/max(data[i])
data

                           hp     seats  auto  cool
1985 Chevy Blazer    0.255333  0.428571   1.0   1.0
2001 Honda Odyssey   0.140000  1.000000   0.0   0.0
2008 Honda Civic     0.100000  0.714286   0.0   0.0
2011 Dodge Charger   0.213333  0.714286   0.0   1.0
2017 Bugatti Veyron  1.000000  0.285714   1.0   NaN

We can also use sklearn's [StandardScaler](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) method to standardize the data.

Standardization of a dataset is a common requirement for many machine learning estimators: they might behave badly if the individual feature do not more or less look like standard normally distributed data (e.g. Gaussian with 0 mean and unit variance).

In [4]:
# Normalize data by removing the mean and scaling to unit variance from each feature

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

data_unitnorm= pd.DataFrame.from_dict(cars_dict, orient="index")

for i in ['hp','seats','auto']:
  feature_data = data_unitnorm[i].values.reshape(-1,1)
  scaler.fit(feature_data)
  data_unitnorm[i]=scaler.transform(feature_data)
data_unitnorm

                           hp     seats      auto  cool
1985 Chevy Blazer   -0.259004 -0.802955  1.224745   1.0
2001 Honda Odyssey  -0.604742  1.491202 -0.816497   0.0
2008 Honda Civic    -0.724651  0.344124 -0.816497   0.0
2011 Dodge Charger  -0.384908  0.344124 -0.816497   1.0
2017 Bugatti Veyron  1.973305 -1.376494  1.224745   NaN

Now create a function that will calculate the euclidean distance between two data points (you can assume the data points will be arrays of the same length).

In [0]:
# Distance function using formula for euclidean distance

def euclidean_dist(datum1, datum2):
    sum = 0
    for i in range(datum1.shape[0]):
      sum += (datum1[i] - datum2[i])**2
    distance = sum**0.5
    return(distance)

In the cell below, calculate the distance between the Bugatti and each other car using euclidean_dist. Remember not to use row three (cool/uncool label) when computing distance.

In [6]:
# FYI: This is how you can call a specific row by name and sub-select features
bugatti = data.loc["2017 Bugatti Veyron"][["hp","seats","auto"]].values
print(bugatti)

for i in cars_dict:
  car = data.loc[i][["hp","seats","auto"]].values
  print("Bugatti - " + i + ": " + str(euclidean_dist(bugatti, car)))
  
print()
bugatti2 = data_unitnorm.loc["2017 Bugatti Veyron"][["hp","seats","auto"]].values
for i in cars_dict:
  car = data_unitnorm.loc[i][["hp","seats","auto"]].values
  print("Bugatti - " + i + ": " + str(euclidean_dist(bugatti2, car)))

[1.         0.28571429 1.        ]
Bugatti - 2008 Honda Civic: 1.4119750243498486
Bugatti - 2011 Dodge Charger: 1.3425788296529182
Bugatti - 1985 Chevy Blazer: 0.7582457436146612
Bugatti - 2001 Honda Odyssey: 1.4999346924558592
Bugatti - 2017 Bugatti Veyron: 0.0

Bugatti - 2008 Honda Civic: 3.7955443494326357
Bugatti - 2011 Dodge Charger: 3.5620726215795644
Bugatti - 1985 Chevy Blazer: 2.304809761974404
Bugatti - 2001 Honda Odyssey: 4.363103710427404
Bugatti - 2017 Bugatti Veyron: 0.0

For the first version of normalization (dividing by the max), you should get the following distances (rounded to the thousandths palce):

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bugatti - Blazer = 0.758

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bugatti - Odyssey = 1.500

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bugatti - Civic = 1.412

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bugatti - Charger = 1.343

For the second version of normalization (standard norm), ou should get the following distances (rounded to the thousandths palce):

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bugatti - Blazer = 2.305

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bugatti - Odyssey = 4.363

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bugatti - Civic = 3.796

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bugatti - Charger = 3.562

Notice that (in this case) both normalization techniques yielded the same order of cars nearest-to-farthest.  This will not always be the case!

Because the distance between the Bugatti and Blazer is the smallest, if k = 1, we would classify the Bugatti as cool. If k = 4 we would not be able to classify the Bugatti in either category using the "majority vote" technique unless we had in place a tiebreaker protocol. Generally speaking, larger values of *k* reduce noise, but also make the boundaries between classes less distinct. The best value of *k* will depend on your dataset and your prediction needs.

# Predicting Diabetes in Pima Heritage Dataset

Next we will see if we can use k-NNA to predict whether or not a patient has diabetes given some medical information about them. Load and view the data in the cell below.

In [7]:
# Data Loading and preprocessing

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names=names)

#  'preg': number of pregnancies  
#  'plas': plasma glucose concentration 
#  'pres': blood pressure 
#  'skin': skin thickness
#  'test': Insulin
#  'mass': BMI
#  'pedi': diabetes pedigree function
#  'age': age
#  'class': '0' means does not have diabetes and '1' means has diabetes


# look at the first 10 rows
data.head(10)

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1
5     5   116    74     0     0  25.6  0.201   30      0
6     3    78    50    32    88  31.0  0.248   26      1
7    10   115     0     0     0  35.3  0.134   29      0
8     2   197    70    45   543  30.5  0.158   53      1
9     8   125    96     0     0   0.0  0.232   54      1

Now, let's clearly define which columns will act as explanatory variables, and which column will be the target value, and split the dataset between your training data and testing data.  Let's try an 80-20 split and use sklearn's [train_test_split](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) method (set random_state = 0 so we get the same output each time).

In [8]:
from sklearn.model_selection import train_test_split

X = data.loc[:,"preg":"age"]
y = data.loc[:,"class"]

x_training, x_testing, y_training, y_testing = train_test_split(X, y, test_size = 0.2, random_state = 0)

print(x_training.shape, y_training.shape)
print(x_testing.shape, y_testing.shape)

(614, 8) (614,)
(154, 8) (154,)

Let's not forget to normalize the data!

In [9]:
scaler = StandardScaler()

for i in ["preg", "plas", "pres", "skin", "test", "mass", "pedi", "age"]:
  temp = x_training[i].values.reshape(-1,1)
  scaler.fit(temp)
  x_training[i]=scaler.transform(temp)
  
  temp2 = x_testing[i].values.reshape(-1,1)
  scaler.fit(temp2)
  x_testing[i] = scaler.transform(temp2)
  
x_training.head()

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

,preg,plas,pres,skin,test,mass,pedi,age
603,0.908329,0.915694,0.449124,0.522226,0.373635,0.378526,0.677404,1.699558
118,0.036447,-0.751822,-0.472301,0.148149,-0.699657,-0.506672,-0.070497,-0.965692
247,-1.126063,1.387632,1.063407,0.771611,5.092711,2.540941,-0.118555,-0.882403
157,-0.835435,-0.374271,-0.677062,0.023456,0.450299,-0.886043,1.100914,-0.882403
468,1.198956,-0.028183,-3.543717,-1.285816,-0.699657,-0.279050,-0.851438,0.366933

This predict method needs to compute the euclidean distance between the “new” observation and all the data points in the training set. Then, it assigns the corresponding label to the observation. Finally, it selects the K nearest ones and performs a "majority vote."

In [15]:
def predict(x_training, y_training, x_test_sample, k):
    # create list for distances and targets 
    distances = []
    targets = []
    
    # use previously made euclidean distance function to calculate distance to all samples in training set
    for q in list(x_training.index):
      distances.append([euclidean_dist(x_test_sample, x_training.loc[q]), q])
      
    # sort distances (smallest to largest)
    distances = sorted(distances)
    
    # make a list of the k neighbors'targets
    for i in range(k):
      dix = distances[i][1]

         preg      plas      pres      skin      test      mass      pedi  \
603  0.908329  0.915694  0.449124  0.522226  0.373635  0.378526  0.677404
118  0.036447 -0.751822 -0.472301  0.148149 -0.699657 -0.506672 -0.070497
247 -1.126063  1.387632  1.063407  0.771611  5.092711  2.540941 -0.118555
157 -0.835435 -0.374271 -0.677062  0.023456  0.450299 -0.886043  1.100914
468  1.198956 -0.028183 -3.543717 -1.285816 -0.699657 -0.279050 -0.851438
193  2.070839  0.443755 -3.543717 -1.285816 -0.699657  2.540941  0.334992
306  1.780211  1.261782 -0.062779  0.148149  0.424744 -0.848106 -0.421920
319  0.617702  2.300046  0.449124 -1.285816 -0.699657 -1.101020 -1.013633
97  -0.835435 -1.569848 -1.086584 -0.163583 -0.052274 -1.493037 -0.430931
530 -0.544808  0.034742 -0.472301 -0.163583  0.203271 -0.304341  0.752494
327  1.780211  1.828108  0.039602 -1.285816 -0.699657  0.365881 -0.800376
619 -1.126063 -0.059646 -3.543717 -1.285816 -0.699657  0.024447 -0.977590
518  2.652094 -1.412536 -0.472301 -1.285816 -0.699657  0.075030 -0.860449
632 -0.544808 -0.311346 -0.472301 -1.285816 -0.699657 -0.759586 -0.370859
524 -0.254181  0.129130 -0.574682 -1.285816 -0.699657 -0.076719 -0.947554
536 -1.126063 -0.500121  1.063407 -1.285816 -0.699657 -0.329633 -0.809387
597 -0.835435 -1.003522 -2.315150 -0.101237 -0.486702 -0.557255  0.277923
462  1.198956 -1.475461  0.039602  1.208035 -0.282266  0.391172  0.716451
17   0.908329 -0.437196  0.244363 -1.285816 -0.699657 -0.329633 -0.638181
739 -0.835435 -0.594509  0.244363 -1.285816 -0.699657  0.922291 -0.521040
263 -0.254181  0.663993  0.551504 -0.350622 -0.699657  0.024447 -0.800376
241  0.036447 -0.940597  0.039602  0.709265  0.049944  0.112967 -0.061486
344  1.198956 -0.814747  0.141982 -1.285816 -0.699657  0.580858  0.055655
302  0.327074 -1.381073  0.653885  1.270381 -0.341893  0.454401 -0.932535
704  0.036447 -0.342809  0.346743 -0.038890  0.152162 -0.481381 -1.046673
240 -0.835435 -0.940597 -0.267540  0.210495 -0.699657 -0.380215 -0.824405
170  0.617702 -0.594509  0.653885 -1.285816 -0.699657 -0.177884 -0.860449
691  2.652094  1.167394  2.291973 -1.285816 -0.699657  1.276371 -0.629170
490 -0.544808 -1.192298 -0.216350  0.459880 -0.137456  0.580858  0.488176
45  -1.126063  1.859570 -0.165159  1.145689 -0.699657  1.238434  4.284750
..        ...       ...       ...       ...       ...       ...       ...
448 -1.126063 -0.531584 -0.267540  1.020996 -0.154493  0.176195  0.130745
431 -0.254181 -1.003522  0.244363 -0.288275  0.024389 -0.228467  0.253894
709 -0.544808 -0.877672 -0.267540  0.709265  0.663253  0.732606  0.623339
115  0.036447  0.789843  1.165787 -1.285816 -0.699657 -0.127301  0.217850
72   2.652094  0.160592  1.063407 -1.285816 -0.699657  1.415474  0.350010
537 -1.126063 -2.010324 -0.472301 -1.285816 -0.699657 -1.328643  0.806560
677 -1.126063 -0.877672 -0.472301 -1.285816 -0.699657  0.391172 -0.611148
753 -1.126063  1.891033  0.961026  1.457420  3.644619  1.402828 -0.734297
174 -0.544808 -1.443998 -0.267540  0.210495 -0.231156 -0.316987 -0.289761
87  -0.544808 -0.657434 -0.062779  0.272841 -0.094865  0.795834 -0.427928
551 -0.254181 -1.160835 -0.062779  0.584572  0.203271 -0.038782  0.374039
486 -0.835435  0.569606 -0.369921  1.270381  3.389073  1.074040  0.208840
705  0.617702 -1.286685  0.551504  0.958650 -0.699657  0.960229 -0.869459
314  0.908329 -0.374271  0.551504  0.646919 -0.699657  0.467046  1.983978
396 -0.254181 -0.783284 -0.677062  0.833958  0.279935 -0.949272  1.434316
600 -0.835435 -0.405734  0.961026 -0.101237 -0.699657 -0.645775 -0.199653
472 -1.126063 -0.059646 -0.165159  0.397534 -0.699657  0.833772 -0.623163
70  -0.544808 -0.657434 -0.165159 -0.038890  0.066980  0.087675  1.203037
599 -0.835435 -0.374271 -1.598487 -0.163583  0.322526 -1.151603 -0.178627
754  1.198956  1.041544  0.449124  0.709265 -0.699657  0.024447 -0.070497
277 -1.126063 -0.531584 -0.267540  0.148149  0.288453 -0.557255 -0.037457
723  0.327074 -0.122571  0.858646  0.584572  0.194753  0.871709 -0.647192
9    1.198956  0.129130  1.370548 -1.285816 -0.699657 -4.072759 -0.704260
359 -0.835435  2.362971  0.346743  0.958650  1.421372  0.542921  1.227066
707 -0.544808  0.192055 -1.188965  0.023456  2.153936  0.277361 -0.872463
763  1.780211 -0.625972  0.346743  1.706805  0.833617  0.087675 -0.887481
192  0.908329  1.198857 -0.165159 -1.285816 -0.699657 -0.228467 -0.250714
629  0.036447 -0.846210 -0.216350  0.085802 -0.699657 -0.949272 -0.956564
559  2.070839 -1.129373  0.244363 -1.285816 -0.699657 -0.266404 -0.500014
684  0.327074  0.475218  0.653885 -1.285816 -0.699657 -4.072759  0.521216

          age
603  1.699558
118 -0.965692
247 -0.882403
157 -0.882403
468  0.366933
193  0.533511
306  1.116535
319  2.116003
97  -0.965692
530 -0.965692
327  0.283644
619 -0.799114
518  0.616800
632 -0.882403
524 -0.799114
536  1.033246
597 -1.048981
462  0.450222
17  -0.216090
739  0.700089
263  2.449160
241 -0.965692
344  1.949425
302  0.117066
704 -0.549247
240 -1.048981
170  0.200355
691  0.866667
490 -0.799114
45  -0.715825
..        ...
448 -0.965692
431  0.366933
709 -0.882403
115  2.282581
72   0.700089
537  2.782316
677 -0.715825
753 -0.632536
174 -0.049512
87  -0.632536
551 -0.715825
486 -1.048981
705 -0.465958
314  0.783378
396  0.450222
600 -0.799114
472 -0.965692
70  -0.465958
599 -0.632536
754  0.949956
277 -0.882403
723  0.700089
9    1.699558
359 -0.382668
707 -0.965692
763  2.449160
192  0.200355
629 -1.048981
559  0.117066
684  2.948894

[614 rows x 8 columns]
603
118
247
157
468
193
306
319
97
530
327
619
518
632
524
536
597
462
17
739
263
241
344
302
704
240
170
691
490
45
750
62
78
366
301
382
140
463
762
127
564
375
663
144
268
21
609
511
35
473
255
534
77
566
312
465
109
553
299
101
315
92
243
397
294
504
400
367
755
231
211
436
165
188
334
758
34
580
418
764
363
757
636
155
390
761
358
535
200
66
567
540
625
12
161
710
531
666
252
293
613
159
711
745
447
229
533
585
467
700
590
680
15
245
337
6
522
520
104
453
402
701
90
678
401
505
218
696
652
205
389
190
494
483
194
484
132
233
173
178
741
579
206
441
96
657
333
749
89
407
179
0
46
171
730
432
107
133
621
223
477
102
108
213
489
356
246
478
466
125
454
549
412
620
224
26
360
614
743
346
3
134
325
434
186
492
295
641
428
604
689
225
628
330
425
332
369
695
521
731
497
516
485
392
576
112
748
673
20
65
298
126
259
569
752
339
642
137
501
7
342
702
309
637
532
185
523
353
460
153
54
30
424
682
100
679
631
724
237
665
56
60
502
262
435
264
712
458
208
391
506
449
167
38
635
686
627
300
722
495
650
163
124
154
336
59
493
304
716
601
343
592
311
427
474
158
51
715
767
517
361
457
658
219
615
308
74
282
561
348
519
4
616
437
596
487
674
5
141
558
135
630
378
685
22
692
276
284
270
426
732
281
420
220
693
320
439
372
120
81
751
13
481
455
742
734
160
747
238
379
513
538
440
545
571
195
191
116
584
765
164
106
16
63
470
384
708
105
542
491
719
329
475
480
498
345
668
405
570
93
433
83
647
656
414
766
557
699
322
357
69
514
509
340
221
713
146
289
29
114
508
618
176
168
347
376
681
669
654
587
189
136
446
644
254
676
290
721
649
232
33
88
44
341
61
733
199
429
573
394
297
73
393
547
541
655
690
645
217
539
634
421
138
212
646
643
664
703
234
67
24
381
216
129
349
111
166
207
438
552
274
651
591
612
525
287
469
326
121
507
228
595
445
117
464
25
110
149
152
528
461
598
139
260
323
688
248
450
410
607
19
328
296
269
226
94
515
280
286
589
726
444
184
371
670
746
275
717
182
32
80
307
11
43
86
36
58
41
411
562
209
148
594
123
574
98
377
130
23
667
555
370
512
383
201
368
554
610
387
292
256
606
197
95
738
759
169
581
305
560
373
227
660
143
180
131
729
47
324
203
84
633
565
611
398
91
82
430
119
291
57
321
257
727
442
42
617
388
335
273
488
550
53
718
128
28
183
459
510
675
151
244
714
543
544
639
697
265
288
423
147
659
177
99
448
431
709
115
72
537
677
753
174
87
551
486
705
314
396
600
472
70
599
754
277
723
9
359
707
763
192
629
559
684

In [0]:
def knn(x_training, y_training, x_testing, k):
    
    ## Your code here

In [0]:
start = time.time()
predictions_slow = knn(x_training, y_training, x_testing, k=5)

print('Took {} seconds'.format(time.time() - start))
predictions_slow

# Using sklearn to speed up normalizing and distance finding

Luckily for us, sklearn has some quick and easy functions for normalizing the data, finding Euclidean distances, training, and testing with k-NNA. Try k = 5 to start.

In [0]:
from sklearn.neighbors import KNeighborsClassifier

# Create Model with k nearest neighbors
knn = KNeighborsClassifier(n_neighbors=5)

# Train/fit model with training data
knn.fit(x_training, y_training)

# Make predictions on the test data using the fitted model
start = time.time()
predictions_fast = knn.predict(x_testing)

print('Took {} seconds'.format(time.time() - start))
predictions_fast

Check sklearn's predictions and make sure they match yours.  Sklearn is faster, but you should get the same answers.

### Evaluating classification performance
Let's see how well our classifier did by looking at the confusion matrix and F1 score.

In [0]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

## Your code here

You should get F1 = 0.659. Notice that this classifier is pretty good at classifying negative samples (compare TN to FP), but we are not very good at classifying positive samples (compare TP to FN).

Spend a few minutes trying to increase the F1 score as much as you can by changing k and the features of the data you are using to predict values.

* What set of features and values of k did you find to be the most optimal?
* Why is choosing the right features so important for prediction accuracy? 
* What other model hyperparameters (other than k) might we be able to tune?
* How might we use non-numerical data columns in our model (if we had any)?

# Pros and Cons of k-NNA

## Pros
* Non-parametric (can be used with data that does not fit a normal distribution)
* Conceptually simple and relatively simple to instantiate
* Little to no "training" time 
* A good starting point/baseline classifier 

## Cons
* Slow "testing" phase compared to other predictors/classifiers 
* Degrades with high-dimension data (because there is less difference between closest and furthest neighbors)
* Unclear how to handle non-numeric features
* Doesn't handle data with skewed class distribution well (if one class is extremely dominant in the training data, it will dominate the "voting majority" for classifying new data)
* Features that are not of the same scale can (should) be normalized, but this introduces another model hyperparameter (i.e., which normalization method is appropriate?)
* Does not take into account feature correlation

---



From these exercises and the pros and cons listed above, here is when it is most useful to use k-NNA:
* Datasets with many data points and few dimensions (but can become very slow as well)
* Datasets that are non-parametric
* When you want a quick and easy classifier that does not have to be optimal (perhaps to use as a baseline for other models)


Lastly, there are many other types of NNAs and there are many other ways to instantiate the k-NNA. For example, we could have used a weighted voting system (nearer neighbors' votes carry more weight) instead of a majority voting system to classify. Additionally, we could have used a different distance measurement or a different error measurement.